### ISSUE TITLE
[multi-approvers] PRs from forks can't access token secret

### ISSUE THREAD

**Issue by meltsufin** [abcxyz/actions#70]
We are trying to use the "using a stored secret to get the token" option for the multi-approvers action. However, it doesn't work when following the documented configuration.

>Multi-approvers action failed: input required and not supplied: token"

```yaml
name: 'multi-approvers'

on:
  pull_request:

# ... skip some lines for brevity

jobs:
  multi-approvers:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Multi-approvers'
        uses: 'abcxyz/actions/.github/actions/multi-approvers'
        with:
          team: 'github-team-slug'
          token: '${{ secrets.MULTI_APPROVERS_TOKEN }}'
```

The reason seems to be that the GitHub `pull_request` trigger doesn't make secrets available to the workflow if the PR is from a fork, rather than a branch in the repository. However, external contributors will always use forks to create PRs. One workaround is to use the `pull_request_target` trigger, but it has [potential security risks](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/).
