### ISSUE TITLE
[multi-approvers] unexpected event [pull_request_target].

### ISSUE THREAD

**Issue by meltsufin** [abcxyz/actions#78]
### TL;DR

When trying to use the `pull_request_target` event type with the multi-approvers action, I get this error:
`Error: Multi-approvers action failed: unexpected event [pull_request_target].`

### Environment Details

```yaml
name: 'multi-approvers'

on:
  pull_request_target:

# ... skip some lines for brevity

jobs:
  multi-approvers:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Multi-approvers'
        uses: 'abcxyz/actions/.github/actions/multi-approvers'
        with:
          team: 'github-team-slug'
          token: '${{ secrets.MULTI_APPROVERS_TOKEN }}'
```

### Additional information

This is a follow-up to #70.
I believe the issue is here: https://github.com/abcxyz/actions/blob/907af59d0741b6dd13d84c65514f35ef970747bd/.github/actions/multi-approvers/src/multi-approvers.ts#L25.
