### ISSUE TITLE
[multi-approvers] Workflow not triggered on PR approval for forked PRs

### ISSUE THREAD

**Issue by meltsufin** [abcxyz/actions#83]
Following the documented configuration for `multi-approvers`, we have the `pul_request_review` trigger configured in our workflow. However, when there is a forked PR from an external contributor, the action doesn't automatically re-run when the PR is approved.

Here's our configuration:
```yaml
name: 'multi-approvers'

on:
  pull_request_target:
    types:
      - 'opened'
      - 'edited'
      - 'reopened'
      - 'synchronize'
      - 'ready_for_review'
      - 'review_requested'
      - 'review_request_removed'
  pull_request_review:
    types:
      - 'submitted'
      - 'dismissed'

permissions:
  actions: 'write'
  contents: 'read'
  id-token: 'write'
  pull-requests: 'read'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  multi-approvers:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Multi-approvers'
        uses: 'abcxyz/actions/.github/actions/multi-approvers@893209ed79a3d2508eeec375ffaf3d21012f5cd0'
        with:
          team: 'multi-approvers'
          token: '${{ secrets.MULTI_APPROVERS_TOKEN }}'
```
